### PR TITLE
[WIP] Use last created build to determine status image

### PR DESCRIPTION
**Pull request by Aaron1011**
Don't merge this yet.

### CODE REVIEW

**Comment by JamesMGreene** [comment]
Ping!

@Aaron1011's last comment sounds like to me after a cursory glance. Can anyone else confirm? @henrikhodne @joshk @BanzaiMan @svenfuchs

**Comment by joshk** [comment]
Sorry, I'm going to close this for now as we have some big changes in the works which will fix this on the UI level first, then in the back end code.

**Comment by JamesMGreene** [comment]
@joshk Any publicly accessible reference for those incoming changes that I can track?

**Comment by joshk** [comment]
Not at the moment sorry. If you would like to apart of some UI testing send an email to support. (the page I am user testing will give you some insight into what is coming in Feb)

**Comment by Aaron1011** [comment]
My head is spinning with all this activity on a PR I made over a year ago :)

**Pull request closed without merging**
