### PR TITLE
Skip GitHub revert branches

### PR DESCRIPTION
**Pull request by BanzaiMan**
The branch names have the form `revert-NNNN-BRANCH`.

Fixes https://github.com/travis-ci/travis-ci/issues/2749.

### CODE REVIEW

**Comment by joshk** [comment]
Can you test on staging, showing the 'before' and 'after', and then we can plan in the deploy to prod?

**Comment by BanzaiMan** [comment]
OK. It took a bit more work, but I got it working on staging.

With @4736ff1, we get

banzaiman_travis_staging_test_-_travis_ci

**Comment by joshk** [comment]
@BanzaiMan is there an example of the 'before', where we test the branch and PR?

Also, maybe the message can be improved, something like 'Pull Request reverted on GitHub' ?

**Comment by BanzaiMan** [comment]
You bet. https://staging.travis-ci.org/BanzaiMan/travis_staging_test/requests

banzaiman_travis_staging_test_-_travis_ci

**Pull request closed without merging**
