### PR TITLE
Add smalltalk_vm key

### PR DESCRIPTION
**Pull request by fniephaus**
See https://github.com/travis-ci/travis-build/pull/1101.

### CODE REVIEW

**Comment by fniephaus** [comment]
> [Bundler could not find compatible versions for gem "addressable"](https://travis-ci.org/travis-ci/travis-core/jobs/251026658#L225)

This seems unrelated to the PR.

**Comment by fniephaus** [comment]
@BanzaiMan any chance to get this merged anytime soon?

**Comment by krono** [comment]
@fniephaus can you restart that job?

**Comment by fniephaus** [comment]
I'm afraid I can't, because I don't have permission to restart jobs for this repo.

**Comment by BanzaiMan** [comment]
Sorry for the long delay.

This has been implemented separately, and it should work now.

**Pull request closed without merging**
