### PR TITLE
Allow PR notifications to be turned off for Slack

### PR DESCRIPTION
**Pull request by malept**
Similar to the HipChat implementation (5bebb20).

Fixes travis-ci/travis-ci#2515.

### CODE REVIEW

**Comment by joshk** [comment]
I'm sorry but we can't add this right now.

We are working on moving this to the UI instead.

Thank you for taking the time to create this PR though!

**Comment by malept** [comment]
It's been over nine months, and this is a problem for our team. What is the timeframe/priority on this feature? It is not listed on http://next.travis-ci.com/ as far as I can tell.

**Comment by joshk** [comment]
Hi @malept 

I'm sorry for our delay on getting to this, some road blocks got in our way.

I am going to follow up with the Slack team to see if this is something we can do with them.

**Comment by joshk** [comment]
Sorry, didn't mean to reopen this.

**Pull request closed without merging**
