### PR TITLE
Use a transaction and advisory lock when using the UpdateJob service

### PR DESCRIPTION
**Pull request by joshk**
This adds an the use of Postgres transactions and advisory locks when processing job events from the worker.

Please see https://github.com/travis-ci/travis-hub/pull/42 for more information

### CODE REVIEW

**Comment by joshk** [comment]
This is now ready for review!

**Comment by henrikhodne** [comment]
Two things I thought of just now:

- Is the service talking to any other third-party services? The serializable transaction won't fail until you try to commit, in which case the database will roll back, but things like pusher messages are still sent?
- If the `commit` method fails and raises an exception, we still call rollback. What will happen in that case?

**Comment by joshk** [comment]
- not that I'm aware of. Pusher messages are sent `after_commit`.
- we will retry, you can see this in Hub.

**Comment by henrikhodne** [comment]
> we will retry, you can see this in Hub.

I was more referring to us just sending `ROLLBACK` outside of a transaction, but some cursory testing shows that it'll raise a new exception, which will hide the original transaction on `COMMIT`, which might not be what we want?

**Comment by joshk** [comment]
Sending `ROLLBACK` outside of a transaction? When would that happen?

**Comment by joshk** [comment]
So, I have tried to test this over and over on staging, and I think everything is working fine. But then I saw two jobs and builds not getting updated correctly.

But I haven't been able to replicated this since, so not sure how that happened.

I tested in the console if the `SERIALIZABLE` transaction and advisory locks didn't play nice, but I don't think that is the case.

I'll continue to push load through staging to try and replicate the issue.

**Comment by henrikhodne** [comment]
Actually, ignore my previous comment. `ROLLBACK`-ing with no transaction doesn't error, it'll just print a warning:

```
>> conn.exec("ROLLBACK")
NOTICE:  there is no transaction in progress
=> #<PG::Result:0x007fd09f6e27c0 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
```

**Comment by joshk** [comment]
Updated and tested heavily on staging. I can not replicate the issue I was seeing earlier.

I think this is good to go.

**Comment by joshk** [comment]
I'll merge and deploy this tomorrow to .org and .com

**Comment by BanzaiMan** [comment]
@joshk Is there a blocker for merging and deploying this?

**Pull request merged**
