### PR TITLE
Invalidated repos

### PR DESCRIPTION
**Pull request by svenfuchs**
* ignores repos which are not accessible on GitHub on various repository scopes
* reduces key size during tests to reduce test run time
* comments broken pusher event handler spec (https://github.com/travis-ci/travis-core/commit/f56848ffb2fea94ff79a3cd9892ea2e4fa7de384#commitcomment-12006268, @drogus, could you have a look at this?)

### CODE REVIEW

**Comment by joshk** [comment]
is this supposed to include `deleted_at` and `deleted_by`?

**Comment by svenfuchs** [comment]
@joshk nope, removed them from the structure

**Comment by joshk** [comment]
I like the simplicity of this

**Comment by rkh** [comment]
Looks good. Do we have code somewhere that sets `invalidated_at`? Guess that's the more tricky part.

**Pull request merged**
