### PR TITLE
add pushover notification support

### PR DESCRIPTION
**Pull request by jantman**
This adds support for notifications via Pushover ( https://pushover.net/ )

This CR is a companion to https://github.com/travis-ci/travis-tasks/pull/28 ; see that for most of my description and commentary.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@jantman Hello there. Do you have some time tomorrow (Wednesday, July 15) or Thursday during the US work hours? I would like to push this to staging and test it.

**Comment by jantman** [comment]
@BanzaiMan sure, that would be great! I can help pretty much any time other than 2:30-4 PM Eastern, if it's not too involved. If it's going to be more than making a few test builds, I'll probably have to do it either before 10am Eastern, 11am-2pm, or after 4pm.

I can usually be reached on freenode irc as 'jantman'.

I've synced over my profile and repos on staging, and setup a sample .travis.yml for this on a branch in one of my repos (see the above referenced commit).

**Comment by BanzaiMan** [comment]
@jantman Super. Let's try after 4 PM tomorrow, then! Thank you.

We will need a repo set up on https://staging.travis-ci.org. If you have one set up on production (https://travis-ci.org), you can switch it to staging, too (and switch it back to production when we are done testing).

**Comment by jantman** [comment]
Cool, thanks. I've switched https://github.com/jantman/awslimitchecker/ over to staging, and verified that it's building there.

**Comment by BanzaiMan** [comment]
Rolling out to staging at the moment.

**Comment by BanzaiMan** [comment]
OK. It's been deployed. Please test it.

**Comment by jantman** [comment]
@BanzaiMan  Sorry I was a bit late on this. Testing now.

**Comment by jantman** [comment]
One [failed build](https://staging.travis-ci.org/jantman/awslimitchecker/builds/433687) and one [successful build](https://staging.travis-ci.org/jantman/awslimitchecker/builds/433689). The notification settings are in my config, and I _did_ receive the email notifications, but nothing via pushover so far. I'll double-check the encrypted settings to make sure they're done for the staging environment.

**Comment by BanzaiMan** [comment]
I didn't see it go through the logs, either. Looking.

**Comment by jantman** [comment]
You did deploy the other PR as well, I assume?

**Comment by BanzaiMan** [comment]
Yes. Could you restart the builds, please? I'm looking at logs of another app now.

**Comment by jantman** [comment]
both have been rebuilt.

**Comment by jantman** [comment]
I may have an issue in my .travis.yml; trying to confirm now

**Comment by jantman** [comment]
That didn't appear to be the issue; https://staging.travis-ci.org/jantman/awslimitchecker/builds/433691 uses a new .travis.yml with no change.

**Comment by BanzaiMan** [comment]
Hmm. Quite weird. I'm going to add some extra debugging information and have you push a new commit shortly afterwards.

**Comment by jantman** [comment]
Ok, will do. I'm watching my email too, to make sure I don't miss anything. I'm also in #travis on Freenode as jantman.

**Comment by jantman** [comment]
@BanzaiMan whatever you just did, did the trick. My rebuilds of https://staging.travis-ci.org/jantman/awslimitchecker/builds/433689 and https://staging.travis-ci.org/jantman/awslimitchecker/builds/433687 notified me correctly:

screenshot_2015-07-15-17-26-46

[Build 7](https://staging.travis-ci.org/jantman/awslimitchecker/builds/433691) where I made [some changes to .travis.yml](https://github.com/jantman/awslimitchecker/commit/636f918a6116b3731af60a0d90ccdc2aa166b891) appears to be hanging...

**Comment by BanzaiMan** [comment]
Deployed to production! Could you test it one more time, before we announce it? Thanks!

**Comment by jantman** [comment]
@BanzaiMan I'm so sorry, I had a pretty crazy day at work and didn't check my personal email until now. I just tried one test, and it wasn't working, I got email but no pushover. I'll try another set of tests momentarily...

**Comment by jantman** [comment]
@BanzaiMan I'm not getting notifications from prod.
https://travis-ci.org/jantman/awslimitchecker/builds/71319604
https://travis-ci.org/jantman/awslimitchecker/builds/71319851

Both exhibit the same behavior as before the restart of staging... I get emails for them, but no Pushover notification, and my Pushover API key status page confirms no requests for that key today.

**Comment by BanzaiMan** [comment]
Hmm. This is strange. I'll take a look.

**Comment by BanzaiMan** [comment]
Logs show that we invoked the notifier for this build:

```
Jul 16 20:31:46 travis-tasks app/tasks.1:  I [task] type=github_status build=71319851 repo=jantman/awslimitchecker state=pending commit=28968e58b1873c147394fb733632852c804e727c 
Jul 16 20:31:46 travis-tasks app/tasks.1:  I type=github_status build=71319851 repo=jantman/awslimitchecker uuid=66de62ea-167c-4a40-90c0-990e6547efd2 time=0.290 jid=8395aeb91735489514966042 
Jul 16 20:31:57 travis-tasks app/tasks.3:  I [task] type=github_status build=71319851 repo=jantman/awslimitchecker state=pending commit=28968e58b1873c147394fb733632852c804e727c 
Jul 16 20:31:57 travis-tasks app/tasks.3:  I type=github_status build=71319851 repo=jantman/awslimitchecker uuid=59f4a3ee-fdcc-4588-b6ae-950706fcfce5 time=0.278 jid=e471ef3eb684c1b92a3c66f8 
Jul 16 20:32:29 travis-tasks app/tasks.3:  I type=email build=71319851 repo=jantman/awslimitchecker uuid=ed7c2dae-9040-4748-8d5f-7daef15737a7 time=0.330 jid=fef71aea8645a0402f24389d 
Jul 16 20:32:30 travis-tasks app/tasks.1:  I [task] type=github_status build=71319851 repo=jantman/awslimitchecker state=failure commit=28968e58b1873c147394fb733632852c804e727c 
Jul 16 20:32:30 travis-tasks app/tasks.1:  I type=github_status build=71319851 repo=jantman/awslimitchecker uuid=ed7c2dae-9040-4748-8d5f-7daef15737a7 time=0.305 jid=db66aef820902db1b459b17a 
Jul 16 20:32:31 travis-tasks app/tasks.3:  I type=pushover build=71319851 repo=jantman/awslimitchecker uuid=ed7c2dae-9040-4748-8d5f-7daef15737a7 time=0.334 jid=db39bd85c675666ec7e775ed 
```

**Comment by BanzaiMan** [comment]
Same with 71319604.

**Comment by jantman** [comment]
My fault, *again*. When I used `travis encrypt` on the API key and user key, I didn't specify `--org`. Success and failure notifications are now working (see https://travis-ci.org/jantman/awslimitchecker/builds/71329751 and https://travis-ci.org/jantman/awslimitchecker/builds/71329915 and https://travis-ci.org/jantman/awslimitchecker/builds/71330223 ).

I think this was because I couldn't find anything in the docs telling me I needed to add the `--org` flag. Did I just miss this, or should I cut a PR to add that to http://docs.travis-ci.com/user/encryption-keys/ ?

screenshot_2015-07-16-17-45-10

**Comment by BanzaiMan** [comment]
My guess is that you were using the staging environment, and `travis` command remembered it. You'd had to re-encrypt the secrets for switching back to `--org`.

**Pull request merged**
